algoritmo "Aula4_1"
// Função :
// Autor :
// Data : 10/05/2022
// Seção de Declarações 
var
    A, B, C: Inteiro
inicio
// Seção de Comandos
     A <- 2
     B <- 3
     C <- 5
     ESCREVA (A>B)
     ESCREVA (A=B)
     ESCREVA (A<>B)
     ESCREVA (A>2)
     ESCREVA (A>=2)
     ESCREVA (C=A+B)
      ESCREVA (C>=B^A)
      ESCREVA (C<=B^A)
      ESCREVA (B>=C%2)
      ESCREVA (1=C%2)
fimalgoritmo
