algoritmo "Aula12_3"
// Função :
// Autor :
// Data : 07/06/2022
// Seção de Declarações 
var
X, Y: Inteiro
Procedimento Soma(var A, B: Inteiro)
inicio
A <- A + 1
B <- B + 2
EscrevaL("Valor A e: " ,A)
EscrevaL("Valor B e: " ,B)
EscrevaL("A soma entre os dois e: " ,A + B)
FimProcedimento

inicio
// Seção de Comandos
   X <- 4
   Y <- 8
   Soma(X, Y)
   EscrevaL("Valor de X : " ,X)
   EscrevaL("Valor de Y : " ,Y)
fimalgoritmo
